version: "3.9"

services:
  db:
    image: postgres:15
    container_name: dropbox_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dropbox_app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: dropbox_api
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/dropbox_app
      - DROPBOX_REFRESH_TOKEN=seu_token
      - DROPBOX_CLIENT_ID=seu_client_id
      - DROPBOX_CLIENT_SECRET=seu_client_secret

volumes:
  pgdata:
